[colors.bright]
black = "0x65737e"
blue = "0x8fa1b3"
cyan = "0x96b5b4"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xeff1f5"
yellow = "0xebcb8b"

[colors.normal]
black = "0x2b303b"
blue = "0x8fa1b3"
cyan = "0x96b5b4"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xc0c5ce"
yellow = "0xebcb8b"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xd4d4d4"

[font]
size = 10.0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[window.padding]
x = 10
y = 10
