#!/usr/bin/env sh
limelight -m config width 1
limelight -m config radius 12
limelight -m config placement exterior
limelight -m config active_color 0xFFFAF14B 
limelight -m config normal_color 0x00F14B00

